### PR TITLE
CONTRIBUTORS: Add Magnus Back (magnusbaeck) as maintainer

### PR DESCRIPTION
**Pull request by magnusbaeck**
Adding myself as maintainer as suggested by Alvin. @logstash-plugins/logstash-core, please review.

### CODE REVIEW

**Comment by ghost** [comment]
Jenkins standing by to test this. If you aren't a maintainer, you can ignore this comment. Someone with commit access, please review this and clear it for Jenkins to run; then  say 'jenkins, test it'.

**Comment by jsvd** [comment]
LGTM

**Comment by purbon** [comment]
@magnusbaeck I wonder if we should just have a file named maintainers, or rename the contributors one, what do you think? //cc @guyboertje @acchen97

**Comment by guyboertje** [comment]
@purbon, @acchen97 : I think leave as is.  The README should be fixed to actually be about the plugin and include Current Maintainer: ... at the top.

**Comment by guyboertje** [comment]
LGTM

**Comment by purbon** [comment]
I think we can do both, a maintainer info should not be in the contributors
file, is confusing.

/purbon

**Comment by guyboertje** [comment]
@purbon - A maintainer may contribute may or may not contribute code. They certainly will contribute their time (a most valuable resource), intellectual effort and commitment. How loose or tight you want to define "contribute"?

The irony is, by contributing tests or documentation patches one becomes a contributor, so by that logic when one adds oneself to the contributor list - one becomes a contributor. :grinning:

**Comment by purbon** [comment]
@guyboertje I understand that, but why mixing the rol in the contributors file? why not having the maintainer in their file and then duplicated in the contributors file, he is not an special contributor, now is confusing, because is mix up.

**Pull request closed without merging**
