### PR TITLE
Fix contributing.md url in readme

### PR DESCRIPTION
**Pull request by MLabusquiere**
Minor fix : contributing.md had been moved in logstash repo.

### CODE REVIEW

**Comment by MLabusquiere** [comment]
CLA check should be ok now

**Comment by magnusbaeck** [comment]
Thanks! Can you retrigger the CLA check somehow? I don't seem to be able to do it and I can't verify your CLA status by hand. Worst case you can amend the commit and force-push a new one.

**Comment by jsvd** [comment]
Thanks for noticing this, in the reorganization of the markdown files we missed this link in all plugins, so we're going to run a mass  commit for all the repositories. So, because of that this wont be merged, to not interfere with the mass update.

**Comment by ph** [comment]
Yup, I will bundle that into the next mass update

**Comment by MLabusquiere** [comment]
Ok guys.

**Pull request closed without merging**
